## 학습목표
 1. 수치해석 라이브러리인 numpy의 이해 및 사용
 2. 데이터 분석 라이브러이인 pandas의 이해 및 사용

## numpy
 - 파이썬의 대표적인 수치해석 라이브러리
 - 벡터, 행렬등의 최적화된 data structure와 다양한 연산 제공
 - 다른 많은 machine learnig, 혹은 data analysis 패키지들에서 많이 사용 됨

In [4]:
import numpy as np
print(np.__version__)

1.13.1


* **ndarray**
 - numpy의 기본 타입
 - n dimentional array를 의미
 - vector, matrix를 표현
 - numpy.array([])로 생성

In [16]:
arr1 = np.array([1, 3, 4, 6]) # 1차원 벡터 생성
arr2 = np.array([[0, 1, 2], [2, 4, 6]]) # 2차원 행렬 생성

print(arr1, type(arr1))
print(arr2, type(arr2))

print()

print(arr1)
arr2.shape

[1 3 4 6] <class 'numpy.ndarray'>
[[0 1 2]
 [2 4 6]] <class 'numpy.ndarray'>

[1 3 4 6]


(2, 3)

* **arange**
 - 내장 함수 range()와 동일한 기능을 수행함
 - ndarray 반환

In [15]:
arr3 = np.arange(1, 11)
print(arr3, type(arr3))
arr3.shape

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


(10,)

* **linspace**
 - start, end를 n-1개의 균일한 간격으로 분할

In [21]:
# 0 - 10의 범위를 n-1 등분 한다는 이야기
arr4 = np.linspace(0, 100, 5) # end 마지막 포함
print(arr4)
a4 = np.linspace(0, 100, 13)
print(a4)

[   0.   25.   50.   75.  100.]
[   0.            8.33333333   16.66666667   25.           33.33333333
   41.66666667   50.           58.33333333   66.66666667   75.
   83.33333333   91.66666667  100.        ]


* **zeros**
 - 전달된 tuple 사이즈 행렬 반환
 - 0으로 채워짐

In [22]:
print(np.zeros((2, 4)))
print(np.zeros(4))

print(np.zeros((2, 2, 2))) # 차원이 올라갈수록 생각하기 힘드니 괄호의 개수로 봐보자

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[ 0.  0.  0.  0.]
[[[ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]]]


* **ones**
 - 전달된 tuple 사이즈 행렬 반환
 - 1로 채워짐

In [23]:
print(np.ones((3, 3, 2, 7, 8)))
#print np.ones(3)

[[[[[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    ..., 
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]]

   [[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    ..., 
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]]]


  [[[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    ..., 
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]]

   [[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    ..., 
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]]]


  [[[ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
    [ 1.  1.  1. ...,  1.  1.  1.]
   

* **random sub package**
  - 다양한 확률 분포를 이용한 랜덤 숫자로 채워진 ndarray 혹은 단일 값을 생성할 때 주로 사용

In [26]:
print(np.random.rand(3, 2, 3)) # [0, 1) 사이 출력 / rand 가변길이라서 
print(np.random.randn(3)) # 정규분포

[[[ 0.30010605  0.80108486  0.44558656]
  [ 0.62845383  0.23577035  0.7180075 ]]

 [[ 0.16203108  0.16491392  0.93000121]
  [ 0.98673692  0.52148458  0.04904567]]

 [[ 0.09020084  0.79107994  0.72605218]
  [ 0.29392408  0.60020182  0.33602943]]]
[-1.86293679  1.0381419   0.43552201]


In [27]:
a = np.random.rand()

In [5]:
a = np.random.rand(3, 2, 2)
a

array([[[ 0.81426147,  0.94556468],
        [ 0.65770851,  0.92107173]],

       [[ 0.1704136 ,  0.24736764],
        [ 0.96359945,  0.92833396]],

       [[ 0.09272107,  0.60092459],
        [ 0.51746453,  0.99177244]]])

In [6]:
# 임의의 정수 한개 생성 [1, 100] #Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(1, 100)

63

In [7]:
# 임의의 정수 tensor 생성 
np.random.randint(1, 100, size=(4, 3))

array([[37, 71, 99],
       [44, 36, 42],
       [93, 85,  5],
       [86, 31,  5]])

In [8]:
# 범위 지정을 원할 경우 uniform 함수 이용
np.random.uniform(low=1.0, high=2.0, size=(4))

array([ 1.6919777 ,  1.2502314 ,  1.4336582 ,  1.52429926])

In [9]:
# 각 확률분포에 해당하는 함수가 존재
np.random.binomial(10, 0.9)

9

In [13]:
# choice함수를 이용하여 샘플링 가능
np.random.choice(range(10), size=40, replace=True)

array([5, 6, 9, 8, 7, 5, 1, 7, 1, 5, 7, 4, 6, 8, 9, 5, 1, 1, 5, 7, 5, 1, 6,
       5, 0, 8, 2, 7, 9, 4, 3, 2, 1, 4, 0, 1, 6, 1, 2, 0])

* **연습문제)**
 1. 20 - 30 사이의 임의의 정수 4개를 출력하시오(중복 허용)
 2. 20 - 30 사이의 임의의 정수 4개를 출력하시오(중복 x)
 3. 20 - 30 사이의 임의의 실수 4개를 출력하시오
 4. 0.01 - 1 사이의 임의의 실수 4개를 출력하시오 

In [25]:
np.random.choice(range(20, 30+1), size=4, replace=True)

array([27, 22, 24, 22])

In [26]:
np.random.choice(range(20, 30+1), size=(4), replace=False)

array([21, 20, 22, 28])

In [28]:
np.random.uniform(20, 30, size=4)

array([ 23.93330999,  24.27945572,  26.86491621,  20.77594827])

In [29]:
np.random.uniform(0.01, 1, size=4)

array([ 0.94791089,  0.91277127,  0.64647193,  0.82638783])

In [30]:
# 균등하게 나누고 싶을때
n = np.random.uniform(0, 2, size=4)
10 **-n

array([ 0.01005218,  0.03359454,  0.21469083,  0.09420577])

* ** seed ** 
 - 실험, 분석 등을 할 때, 랜덤 값 생성 시, 해당 값을 추후에 또 사용해야 할 경우가 필요
 - 해당 경우에는 seed함수를 미리 호출하여 랜덤한 값을 동일 한 값으로 유지 할 수 있음
 - seed() 함수 호출 시, 정수를 전달

In [36]:
np.random.seed(1) # seed 는 일회성이라 같이 호출을 해줘야함
print(np.random.rand(2, 3))

[[  4.17022005e-01   7.20324493e-01   1.14374817e-04]
 [  3.02332573e-01   1.46755891e-01   9.23385948e-02]]


In [41]:
np.random.randint(1, 101, 10) # seed없어서 바뀜 

array([50, 58,  4, 69, 25, 44, 77, 27, 53, 81])

In [51]:
np.random.seed(0) # 랜덤한 값을 계속 유지하고 싶을 때 사용
print(np.random.rand())

np.random.seed(2) # 랜덤한 값을 계속 유지하고 싶을 때 사용
print(np.random.rand())

0.5488135039273248
0.43599490214200376


* **slicing**
 - 리스트, 문자열 slicing과 동일함
 - 단, ndarray의 차원이 높을 경우에는, 각 차원별로 slicing, indexing 가능

In [52]:
arr1 = np.array([1, 3, 4, 6])
arr2 = np.array([[0, 1, 3], [2, 4, 6], [3, 7, 8]])

In [53]:
print(arr1[0])
print(arr1[1:-1])

1
[3 4]


In [54]:
arr2

array([[0, 1, 3],
       [2, 4, 6],
       [3, 7, 8]])

In [56]:
print(arr2[1, :1]) # 슬라이싱을 하면 벡터 , 차원유지
print(arr2[1, 0]) # 인덱싱 , 스칼라

[2]
2


In [57]:
arr2 = np.array([[0, 1, 3], [2, 4, 6]])

print(arr2[0]) # 1차원 
print(arr2[0, 1]) # 스칼라
print(arr2[1:, :2]) # 2차원, 
print(arr2[:, 2]) 
print(arr2[:, 1:])

[0 1 3]
1
[[2 4]]
[3 6]
[[1 3]
 [4 6]]


* **Boolean selection**
  - bool 리스트로 해당 값이 True인 조건만 필터링

In [60]:
arr = np.array([1, 2, 4, 8, 9, 6, 12, 13])
lst = [1, 2, 4, 8, 9, 6, 12, 13]

print(arr % 2 == 0) # 차원을 올려줌, 연산수행
print(lst % 2 == 0)  # TypeError: unsupported operand type(s) for %: 'list' and 'int'

[False  True  True  True False  True  True False]


TypeError: unsupported operand type(s) for %: 'list' and 'int'

## 중요 

In [62]:
even_mask = (arr % 2 == 0)
print(even_mask)
print(arr[even_mask]) # 참인것만!!!
print(arr[arr % 2 == 0]) # 연산줄임!! 

[False  True  True  True False  True  True False]
[ 2  4  8  6 12]
[ 2  4  8  6 12]


* multiple conditions
 - and, or, not 키워드 사용 불가 (not에 !가 안됨)
 - & - AND 
 - | - OR 

In [63]:
arr[(arr > 7) | (arr <= 5)] 

array([ 1,  2,  4,  8,  9, 12, 13])

In [64]:
arr[(arr % 2 == 0) & (arr <= 8)]

array([2, 4, 8, 6])

* **ndarray operations**
  - scala와의 연산은 전체 원소에 대해 적용
  - 다른 ndarray와의 연산은 element-wise로 적용

In [65]:
arr = np.arange(1, 7) * 5
print(arr)

[ 5 10 15 20 25 30]


In [66]:
arr2 = arr ** 4
print(arr2)
print(arr2 ** 0.5)

[   625  10000  50625 160000 390625 810000]
[  25.  100.  225.  400.  625.  900.]


In [67]:
arr1 = np.arange(0, 30, 3) + 3
arr2 = np.arange(1, 11)
print(arr1, arr2)

print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 * arr1)
#print arr1 ^2 
print(arr1 ** 2)

[ 3  6  9 12 15 18 21 24 27 30] [ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[  3  12  27  48  75 108 147 192 243 300]
[  9  36  81 144 225 324 441 576 729 900]
[  9  36  81 144 225 324 441 576 729 900]


In [68]:
arr1 = np.array([[1, 1], [1, 1]])
arr2 = np.array([[2, 2], [2, 2]])

print(arr1 * arr2)  # 원소끼리의 곱
print(arr1.dot(arr2)) # 행렬 곱

[[2 2]
 [2 2]]
[[4 4]
 [4 4]]


* **logical operator**
  - all()
    - 모든 원소가 조건을 만족 시키면 True, 아니면 False
  - any()
    - 어떤 원소라도 조건을 만족 시키면 True, 아니면 False

In [82]:
arr = np.random.randint(1, 10, size = (4,4))
print(arr)

[[6 5 6 3]
 [7 1 6 8]
 [2 7 8 1]
 [2 3 5 1]]


In [78]:
print(np.all(arr < 7))

False


In [83]:
print(np.any(arr == 9))

False


* **ravel**
  - 다차원배열을 1차원으로 변경 (쭈욱 핌~)

In [88]:
arr = np.array([np.arange(1, 6), np.arange(10, 15)])
print(arr)

[[ 1  2  3  4  5]
 [10 11 12 13 14]]


In [89]:
print(arr.ravel())

[ 1  2  3  4  5 10 11 12 13 14]


* **flatten**
 - 다차원 배열을 1차원으로 변경
 - copy를 생성하여 변경함

In [90]:
print(arr.flatten())

[ 1  2  3  4  5 10 11 12 13 14]


In [91]:
print(arr.flatten('F')) # column을 우선으로 변경

[ 1 10  2 11  3 12  4 13  5 14]


In [92]:
# ravel vs flatten
f_arr = arr.flatten() # copy를 반환
r_arr = arr.ravel() # 원본 ndarray와 메모리 공유 <- 원본이 바뀜

r_arr[0] = 60

print(f_arr)
print(r_arr)
print(arr)

[ 1  2  3  4  5 10 11 12 13 14]
[60  2  3  4  5 10 11 12 13 14]
[[60  2  3  4  5]
 [10 11 12 13 14]]


* **reshaping**
 - array의 shape을 재정렬
 - 이때, 서로의 전체 원소 개수가 맞아야 가능
 - 데이터 정제에 가장 많이 사용
   e.g) 이미지의 경우, 2차원 픽셀로 표현되나, 이것을 ml library로 전달하기 위해 reshape하여 사용

In [87]:
arr = np.arange(1, 16)
print(arr)
arr2 = arr.reshape(3, 5)
print(arr2)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [85]:
print(arr)
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.maximum(arr, np.array([99, 1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 21, 22, 23, 24])))
print(np.std(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sum(arr))
print(np.sqrt(arr))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
1
8.0
8.0
15
[99  2  3  4  5  6  7  8  9 10 20 21 22 23 24]
4.32049379894
0
14
120
[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766  3.31662479  3.46410162
  3.60555128  3.74165739  3.87298335]


* **자주 쓰는 numpy 함수**

* **axis**
 - 몇몇 함수에는 axis keyword 파라미터가 존재
 - axis값이 없는 경우에는 전체 데이터에 대해 적용
 - axis값이 있는 경우에는, 해당 axis를 **따라서** 연산 적용

In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr2))

In [ ]:
# 1차원 적용
arr2 = np.array([1, 2, 3])
print(np.sum(arr2, axis=0))

In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

In [ ]:
# 2차원 적용

print(np.sum(arr2, axis=0))
print(np.sum(arr2, axis=1))

In [ ]:
# 3차원 적용
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 1, 1], [2, 2, 2]]] )
print(np.sum(arr2, axis=0))
print(np.sum(arr2, axis=1))
print(np.sum(arr2, axis=2))

 * **numpy broadcasting**
  - 연산시, 차원이 맞지 않은 경우, 적은 차원의 ndarray를 상위 차원으로 broadcast하여 연산 진행

In [ ]:
arr = np.arange(10)
arr2 = np.arange(2, 12)
arr3 = np.arange(10).reshape(2, 5)

arr + arr2 # 기본적으로 element-wise 연산

In [ ]:
arr + 1

In [ ]:
2 ** arr 

In [ ]:
arr ** 2

In [ ]:
arr3

In [ ]:
arr3 + arr[1:6]

In [ ]:
arr3.shape, arr[1:6].shape

In [ ]:
arr3 + 3

* **where 함수**
 - condition에 따라 x, y선별적으로 선택

In [ ]:
a = np.array([1, 2, 4, 9, 10])
b = np.array([0, 4, 9, 8, 7])
a, b

In [ ]:
# 조건이 참이면 a, 거짓이면 b에서 선택
np.where(a > 7, a, b) 

In [ ]:
np.where([True, False, True, True, True], a, b)

In [ ]:
# 조건이 참이면 a, 거짓이면 1로 선택
np.where(a > 7, a, 1)

* **연습문제**
 1. np.random.randn(5, 5)로 생성된 행렬에서 음수값을 0으로 변경하세요
 2. numpy를 이용하여 Math.pi 값을 다시 구해봅시다.
 3. python 기본 리스트 객체로 만든 두 행렬을 곱하는 코드를 작성하시오.

* **linear regression 실습**

* generate random data
 - random package 활용하여 feature와 target 생성

In [ ]:
x = np.random.randn(100)
x.shape, x

In [ ]:
y = 4 * x + 30 + 1.1 * np.random.randn(100)
y.shape, y

* plot data 

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline 

In [ ]:
plt.scatter(x, y, c='r', marker='o')

* create a model

In [ ]:
x = x.reshape(100, 1)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x, y)

* check coefficient, bias(intercept)

In [ ]:
w = model.coef_
b = model.intercept_

w, b

* plot data with our model

In [ ]:
plt.scatter(x, y, c='r', marker='o')
plt.plot(x, w * x + b, 'g-')

* **pandas**
  - http://pandas.pydata.org/
  - Opensource python 고성능 데이터 분석 라이브러리
  - DataFrame, Series 객체가 가장 많이 사용
  - ML library인 scikit-learn과 함께 ML 분석에 많이 사용 됨
  - pip install pandas로 설치
  - 관례적으로 pd 로 임포트

In [ ]:
import numpy as np
import pandas as pd

 * **Series**
  - pandas의 기본 객체 중 하나
  - numpy의 ndarray를 기반으로 인덱싱을 기능을 추가하여 1차원 배열을 나타냄
  - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성
  - 같은 타입의 0개 이상의 데이터를 가질 수 있음

In [ ]:
s1 = pd.Series([1, 2,  20])
print(s1)

In [ ]:
print(s1[0])

In [ ]:
s2 = pd.Series(list(range(1, 6)))
print(s2)

 * **값 및 인덱스 접근**
  - 각가 values, index 속성

In [ ]:
print(s2.values)

In [ ]:
print(s2.index)

* **index 지정하기**

In [ ]:
print(chr(97))
print([chr(i) for i in range(97, 100)])

In [ ]:
print(chr(97))

s3 = pd.Series(list(range(1, 4)), index = [chr(i) for i in range(97, 100)])
print(s3)
print()
print(s3.values)
print()
print(s3.index)

In [ ]:
print(s3[1]) # 기본 인덱스
print(s3['c']) 

* **index 재사용**

In [ ]:
s4 = pd.Series(2, index = s3.index)
print(s4)

In [ ]:
s5 = pd.Series(np.random.randn(5))
print(s5)

In [ ]:
s6 = pd.Series(np.arange(1, 9))
print(s6)

In [ ]:
s7 = pd.Series({'a' : 100, 'b' : 1000, 'c' : 2, 'd' : 6})
print(s7)
print(s7['b'])

* **Series size, shape, unique, count, value_counts**
 - size : 개수 반환
 - shape : 튜플형태로 shape반환
 - unique: 유일한 값만 ndarray로 반환
 - count : NaN을 제외한 개수를 반환
 - value_counts: NaN을 제외하고 각 값들의 빈도를 반환 

In [ ]:
s = pd.Series([0, 1, 1, 2, 3, 4, 5, 6, 7, np.nan])
print(s)

In [ ]:
print(len(s))

In [ ]:
print(s.size)

In [ ]:
print(s.shape)

In [ ]:
print(s.count()) # NaN을 제외한 값을 카운팅

In [ ]:
print(s.unique())

In [ ]:
print(s.value_counts()) # NaN 제외하고 값들을 카운팅 함

* **head, tail, take**
 - head : 상위 n개 출력 기본 5개
 - tail : 하위 n개 출력 기본 5개
 - take : 주어진 인덱스 리스트와 매칭되는 원소만 추출

In [ ]:
s.head() # 상위 5개 출력

In [ ]:
s.head(n = 3)

In [ ]:
s.tail()

In [ ]:
s.tail(n = 2)

In [ ]:
print(s)
print() 
print(s.take([0, 4, 3, 9]))

In [ ]:
s = pd.Series(np.arange(1, 4), index = ['x', 'y', 'z'])
s.take([0, 2])
#s.take(['x', 'z']) #0 - based index만 가능

 * **single value accessing**
  - 인덱스를 이용하여 값 접근 가능
  - 문자열 인덱스가 주어진 경우, 0-based index도 사용 가능
  

In [ ]:
print(s['x']) # 인덱스로 가능

In [ ]:
print(s[1]) # 숫자 인덱스도 가능

In [ ]:
s = pd.Series(np.arange(1, 4), index = [100, 101, 102])
print(s[100])
print(s[0]) # 에러

* **multiple values accessing**
 - 인덱스 리스트, ndarray로 여러 값에 접근 가능

In [ ]:
print(s)
print(s[[100, 102]])

* **loc , iloc**
  - loc[] : index로 값 접근
  - iloc[] : 0 based index로 값 접근

In [ ]:
print(s)

In [ ]:
print(s.loc[100])

In [ ]:
print(s.iloc[0])

In [ ]:
print(s.loc[[100, 102]])

In [ ]:
print(s.iloc[[0, 2]])

In [ ]:
s.loc[[100, 102, 104, 105]]

In [ ]:
# 에러 발생
# 인덱스 4가 없기 때문
s.iloc[[0, 2, 1, 4]] 

* **index를 기준으로 더하기**

In [ ]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
print(s1)

In [ ]:
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])
s2

In [ ]:
print(s1 + s2)

In [ ]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])
a1 + a2

* **산술연산**
 - Series의 경우에도 스칼라와의 연산은 각 원소별로 스칼라와의 연산이 적용
 - Series와의 연산은 각 인덱스에 맞는 값끼리 연산이 적용
   - 이때, 인덱스의 pair가 맞지 않으면, 결과는 NaN 

In [ ]:
print(s1)

In [ ]:
print(s1 ** 2)
print(s1)

In [ ]:
exp = pd.Series(2, s1.index)
print(s1 ** exp)

In [ ]:
s1 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 5})
s2 = pd.Series({'b': 6, 'c': 7, 'd': 9, 'e': 10})

print(s1 + s2)

 * **NaN (Not a Number)**
  - numpy와 비교

In [ ]:
nda = np.array([1, 2, 3, 4, 5])
nda.mean()
np.mean(nda)

In [ ]:
nda = np.array([1, 2, 3, 4, np.NaN])
nda.mean()

In [ ]:
s = pd.Series([1, 2, 3, 4, np.NaN])
print(s.mean())
print(s.mean(skipna=False))

 * **Boolean selection**
  - boolean Series가 []와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함됨

In [ ]:
s = pd.Series(np.arange(1, 10))
s > 5
print(s[s > 5])

In [ ]:
my_logic = s > 5
print(s[my_logic])

In [ ]:
print(s[s > 5])


In [ ]:
#print s > 5 and s < 8
#print s[s > 5 and s < 8]
print(s[(s > 5) & (s < 8)]) # & and , | or

In [ ]:
print((s >= 0).all())
print((s >= 2).all())

In [ ]:
print((s < 2).any())
print(s[s < 2].any())

In [ ]:
print(s)
print() 
print(s[s >= 7].sum())
print((s >= 7).sum())

* **Series 값 변경**
  - 인덱스를 이용하여 변경  


In [ ]:
s = pd.Series([1, 10, 100], index = ['a', 'b', 'c'])
s['d'] = 1000

print(s)

s['d'] = 10000
print(s)

In [ ]:
del s['a']
print(s)

* **Slicing**
 - 리스트, ndarray와 동일하게 적용

In [ ]:
s.value_counts()

In [ ]:
s = pd.Series(np.arange(100, 110), index=np.arange(10, 20))
print(s)
print(s[0:5])
print(s[:5])
print(s[5:])
print(s[-3:])

* **DataFrame**
  - Series가 1차원이라면 DataFrame은 2차원으로 확대된 버젼
  - Excel spreadsheet이라고 생각하면 이해하기 쉬움
  - 2차원이기 때문에 인덱스가 row, column로 구성됨

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame(np.array([[10, 11], [20, 22]]))
print(df)

In [ ]:
df = pd.DataFrame(np.array([2, 1, 2, 3]))
print(df, type(df))

* **shape**
 - row, column에 대한 튜플 값으로 볼 수 있음

In [ ]:
df1 = pd.DataFrame([pd.Series(np.arange(10, 15)) ,
            pd.Series(np.arange(20, 25))])
print(df1)
print(df1.shape)
print() 
print(df1.info())
print() 
print(df1.describe())

In [ ]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), 
                  columns = ['a', 'b'])
print(df)
print(df.columns)
print(df.columns[0], df.columns[1])

df.columns = ['t1', 't2']
print(df)

In [ ]:
df = pd.DataFrame(np.array([[10, 20], [20, 30]]), 
                  columns = ['a', 'b'], index = ['d1', 'd2'])
print(df)
print(df.index)

* **Series dictionary로 부터 생성**

In [ ]:
s1 = pd.Series(np.arange(1, 6, 1))
s2 = pd.Series(np.arange(6, 11, 1))
df = pd.DataFrame({'c1': s1, 'c2': s2})

print(df)

* **csv 데이터로 부터 dataframe 생성**
  - dataframe을 생성하는 가장 보편적인 방법
  - 데이터 소스로부터 추출된 csv(comma separated values) 파일로 부터 df 생성

In [ ]:
sample_file = 'data/sample.csv'

In [ ]:
sample_df = pd.read_csv(sample_file)
sample_df.head(n=3)

In [ ]:
sample_df = pd.read_csv(sample_file, usecols = [0, 1, 2, 3, 7])
sample_df.head()

In [ ]:
sample_df = pd.read_csv(sample_file, index_col = 'Symbol', usecols = [0, 1, 2, 3, 7])
sample_df.head()

In [ ]:
sample_df = pd.read_csv(sample_file, index_col = 'Symbol', 
                        usecols=['Name', 'Symbol', 'Price'])
sample_df.head()

* **data 개수**

In [ ]:
print(len(sample_df))

In [ ]:
print(sample_df.index)
print() 
print(sample_df.columns)

* **dataframe slicing**
  - dataframe의 경우 기본적으로 [] 연산자가 column 선택에 사용
  - 따라서 [0], ['some val'] 과 같이 하면 column 레벨의 데이터 추출
  - 하지만, 유일하게 slicing은 row 레벨로 지원

In [ ]:
print(pd.__version__)

In [ ]:
#apple_df = pd.read_csv('apple.csv', header = None)
apple_df = pd.read_csv('data/apple.csv')
#print apple_df[:10]
apple_df.head()

In [ ]:
print(apple_df['High'])

* **column 선택하기**
  - df에서 특정 컬럼의 데이터만 추출
  - 컬럼 이름일 경우 이름만 사용 가능
  - 컬럼 인덱스일 경우 인덱스의 리스트 사용 가능

In [ ]:
# 숫자 인덱스로 컬럼 셀렉션 확인 할 것 
apple_df[['Date', 'Close', 'Volume']] # 인덱스로도 가능

In [ ]:
print(type(apple_df[[0, 4, 5]]))
print(type(apple_df[[0]]))
print(type(apple_df[['Date']]))
print(type(apple_df[['Date', 'Close']]))
print(type(apple_df['Date']))

In [ ]:
print(apple_df.Date)
print(apple_df.Close)

* **row 선택하기**
  - Seires의 경우 []로 row 선택이 가능하나, **DataFrame의 경우는 기본적으로 column을 선택하도록 설계**
  - [:10]과 같이 slicing의 경우에는 row 선택 가능
  - .loc, .iloc, .ix 의 함수로 row 선택 가능

In [ ]:
print(apple_df[0:10])

print(apple_df.loc[0])


In [ ]:
sample_df = pd.read_csv('sample.csv', index_col = 'Symbol', 
                        usecols = [0, 1, 2, 3, 7])
sample_df

In [ ]:
print(sample_df.loc['MMM'])

In [ ]:
print(sample_df.loc[['MMM', 'MSFT']])

In [ ]:
print(sample_df.iloc[[0, 1, 2]])
print(type(sample_df.iloc[[0, 1, 2]]))

print(sample_df.iloc[0]) 
print(type(sample_df.iloc[0]))

* **boolean selection으로 row 선택하기**

In [ ]:
print(sample_df.Price > 100)
print(sample_df['Price'] > 100)

In [ ]:
sample_df[sample_df['Price'] > 100][['Name', 'Price']]

In [ ]:
print(sample_df[sample_df.Price > 100][['Price']])

In [ ]:
sample_df.head()

* **새 column 추가하기**

In [ ]:
# 새로운 dataframe 생성
copy = sample_df.copy()

# 새로 생성된 프레임에 새로운 컬럼 추가 (기존 컬럼 이용)
copy['TwicePrice'] = sample_df.Price * 2
copy.head()

In [ ]:
copy['ratio'] = copy['Price'] / copy['Book Value']
copy.head()

In [ ]:
# insert 함수를 이용하여 원하는 컬럼 위치에 삽입 가능
copy.insert(1, 'TriplePrice', sample_df.Price * 3)
copy.head()

 * **column 삭제하기**

In [ ]:
print(copy[:2])

# del 키워드로 삭제
del copy['TriplePrice']
print(copy[:2])

 * **row 추가/삭제하기**

In [ ]:
df1 = copy.iloc[0:3].copy()
print(df1)

# append 함수 사용
copy = copy.append(df1)
print(copy.tail())

In [ ]:
# 인덱스가 유일 값을 가져야 하는데???
copy.loc['MMM']

In [ ]:
# drop 함수를 사용하여 해당 row 제거
copy = copy.drop(['ABBV'])
copy.tail()